name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # This should be a list under "branches"

jobs:
  build:
    runs-on: ubuntu-latest  # Correct format

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # Correct action name

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # "username" was misspelled as "usename"
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/dockerized-static-site:latest
